### PR TITLE
Update dawn variant active foreground color to improve text visibility

### PR DESCRIPTION
**Pull request by milanglacier**
Replace the bright green background with purple to improve text visibility and contrast in day theme mode.

Before:
Screenshot 2024-11-08 at 02 03 37

After:
Screenshot 2024-11-08 at 02 04 34

### CODE REVIEW

**Comment by mvllow** [comment]
Thanks for the PR—I'm not familiar with theming this app but are we able to change the foreground of the selected text? Most of our colours for dawn expect a light foreground atop of them, otherwise we use the highlight low/med/high.

**Comment by milanglacier** [comment]
> Thanks for the PR—I'm not familiar with theming this app but are we able to change the foreground of the selected text? Most of our colours for dawn expect a light foreground atop of them, otherwise we use the highlight low/med/high.

Hi, yes, the foreground can be changed. But I think we will need a separate PR for this… since this PR mentioned that it only changes the background.

Do you want to merge this PR firstly and then I submitted another one that changes the foreground.

Or I create another PR that change both BG and FG?

**Comment by mvllow** [comment]
We should probably keep the original pine background and change the foreground to base or surface

**Comment by milanglacier** [comment]
Hi Everyone, sorry for the late reply.

I have updated this patch to restore the original pine background, and use base as the foreground color.

Please see the screenshot:

Screenshot 2024-12-01 at 23 56 26

**Comment by mvllow** [comment]
Thank you very much :)

**Pull request merged**
